[17.0] [MIG] pos_partner_deselection
it-projects-llc/pos-addons pull request #3
Opened 2024-09-28 08:32 UTC by azimkhankuat

[17.0] [MIG] pos_partner_deselection

2024-09-30 09:53 UTC, em230418 requested changes

2024-09-30 09:53 UTC, em230418 commented on pos_partner_deselection/__manifest__.py
> +    "summary": """The module deselects a partner in opened POS on expiry the predefined time interval after the customer was set.""",  # noqa: B950
Добавь тут исключение, чтобы pre-commit не жаловался

2024-09-30 09:53 UTC, em230418 commented on pos_partner_deselection/__manifest__.py
> +            "pos_partner_deselection/static/js/test_pos_deselection.js",
В тестах жалуются, что такого файла нет. Вангую нету src в пути.

2024-09-30 09:53 UTC, em230418 commented on pos_partner_deselection/static/src/js/partner_deselection.js
> +            }
В 14.0 после загрузки POS-а клиент сразу снимается.
Тут через указанное в настройках время. а надо сразу.

2024-09-30 09:53 UTC, em230418 commented on pos_partner_deselection/views/pos_config_view.xml
> +            </xpath>
![Снимок экрана_2024-09-30_14-48-58](https://github.com/user-attachments/assets/7b457b90-6935-4cee-b625-d7f4ad1ee1a0)
Полоска с добавленным полем не на том месте.

В целом предлагаю также рассмотреть вариант размещения этого поля в Configuration -> Settings.

2024-09-30 09:53 UTC, em230418 commented
Тесты надо также исправить, чтобы работали и проходились

2024-10-01 06:58 UTC, em230418 commented on pos_partner_deselection/views/res_config_settings_views.xml
> +            </xpath>
Уже есть какой-то элемент с id="restaurant_section". Предлагаю "pos_partner_deselection" использовать

2024-10-01 06:58 UTC, em230418 commented on pos_partner_deselection/views/pos_config_view.xml
> +</odoo>
Не надо дублировать настройки и там и тут. Надо оставить только в res.config.settings

2024-10-01 06:58 UTC, em230418 commented on pos_partner_deselection/static/src/js/partner_deselection.js
> +            }
От предыдущей реализации надо избавиться.

2024-10-01 06:58 UTC, em230418 commented on pos_partner_deselection/models/res_config_settings.py
> +    )
Если так оставить, то настройка в res.config.settings никак не будет влиять на функционал, ибо поле в самом pos.config-е не меняется.

Пример, как правильно https://github.com/odoo/odoo/blob/17.0/addons/point_of_sale/models/res_config_settings.py
Название поля начинается с pos, используется related и readonly=False

2024-10-01 06:58 UTC, em230418 commented on pos_partner_deselection/models/res_config_settings.py
> +    _inherit = "res.config.settings"
Тут предлагаю оставить название ResConfigSettings

2024-10-01 06:58 UTC, em230418 commented on pos_partner_deselection/models/__init__.py
> +from . import res_config_settings
Раз уж создали файл res_config_settings, то models надо переименовать в pos_config.py

2024-10-01 06:59 UTC, em230418 commented on pos_partner_deselection/static/src/js/test_pos_deselection.js
> +    "use strict";
Тесты не проходят. Вангую тут надо что-то добавить или переписать тест так, как это сделано в модулях point_of_sale.

2024-10-01 07:24 UTC, azimkhankuat commented on pos_partner_deselection/views/pos_config_view.xml
> +            </xpath>
> ![Снимок экрана_2024-09-30_14-48-58](https://private-user-images.githubusercontent.com/52414052/372036508-7b457b90-6935-4cee-b625-d7f4ad1ee1a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NjcwNjIsIm5iZiI6MTcyNzc2Njc2MiwicGF0aCI6Ii81MjQxNDA1Mi8zNzIwMzY1MDgtN2I0NTdiOTAtNjkzNS00Y2VlLWI2MjUtZDdmNGFkMWVlMWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDA3MTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzY2Y1N2EwYmIwMWEzMjEzYjAwNGI3ZmQ5YzUxZWNmNWNiODkyYTRmOWQ4M2EzOGE3ZjIwZWEwZWJlZTc0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fU778ZZYo0Zd09LqvEtfAIlWMeg6EgcmzA_MsliNiWM) Полоска с добавленным полем не на том месте.
> 
> В целом предлагаю также рассмотреть вариант размещения этого поля в Configuration -> Settings.

Я немножко запутался, вчера мы добавили это поле в POS Configurations. Теперь надо оттуда убрать и добавить только в res.config.settings?

2024-10-01 10:13 UTC, em230418 commented on pos_partner_deselection/views/pos_config_view.xml
> +            </xpath>
> Я немножко запутался, вчера мы добавили это поле в POS Configurations. Теперь надо оттуда убрать и добавить только в res.config.settings?

В итоге надо убрать из формы POS и оставить только в res.config.settings.

2024-10-02 10:09 UTC, em230418 commented on pos_partner_deselection/models/__init__.py
> +from . import res_config_settings
Не pos_config_settings, а просто pos_config

2024-10-02 10:09 UTC, em230418 commented on pos_partner_deselection/tests/test_partner_deselection.py
> +        self.main_pos_config.open_ui()
Там тест проваливается при запуске. Есть предположение, что надо запускать под определенным пользователем. Как тут:
https://github.com/odoo/odoo/blob/6182579b8b98c70d25458e990d63e27293eb0ec8/addons/point_of_sale/tests/test_frontend.py#L541

2024-10-03 11:22 UTC, em230418 reviewed
Коммит "[IMP] pos_partner_deselection: tests" и последующий коммит с вьюхой соедени, пожалуйста, с "[MIG] pos_partner_deselection: Migration to 17.0".

2024-10-03 11:22 UTC, em230418 commented on pos_partner_deselection/views/res_config_settings_views.xml
> +            </xpath>
В 14.0 эта настройка находилась в разделе PoS interface.
Перенеси пожалуйста его туда.

Скрин из 14.0.:
![Снимок экрана_2024-10-03_16-11-33](https://github.com/user-attachments/assets/216a669e-9eb4-4f2c-8b3f-9f277d6157a6)

2024-10-03 12:39 UTC, em230418 approved these changes

2024-10-03 12:39 UTC, merged